import dotenv from 'dotenv';
import { connectDB, createBoard, updateBoard } from './db.js';
import mongoose from 'mongoose';

// Load environmental variables
dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/canvas-board';

const seedData = {
  name: 'JavaScript',
  pan: { x: 1200, y: 150 },
  zoom: 0.35,
  drawings: [],
  cards: [
    {
      id: 'types-primitive-non',
      x: -1500,
      y: 0,
      width: 340,
      height: 270,
      title: '1. Primitive & Non-Primitive',
      content: 'Primitive types are immutable and stored directly in the call stack. They represent a single value.\n\nNon-Primitive types (objects, arrays, functions) are mutable and stored in the heap, with a pointer/reference in the stack.',
      code: 'let name = \'Alice\'; // Stack\nlet user = { name: \'Alice\' }; // Reference in stack, object in Heap',
      tags: ['basics', 'memory', 'types'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'types-pass-val-ref',
      x: -1500,
      y: 320,
      width: 340,
      height: 270,
      title: '2. Pass by Value & Reference',
      content: 'Primitives are passed by value: a copy of the value is made.\n\nNon-primitives are passed by reference: a copy of the memory pointer is made, meaning modifications affect the original object.',
      code: 'let a = 1; let b = a; b = 2; // a is still 1\nlet x = [1]; let y = x; y.push(2); // x is now [1, 2]',
      tags: ['memory', 'references'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'types-coercion-conversion',
      x: -1500,
      y: 640,
      width: 340,
      height: 270,
      title: '3. Type Coercion & Conversion',
      content: 'Type Conversion (Explicit): Manually converting types (e.g. String(123)).\n\nType Coercion (Implicit): Automatic type conversion by the JS engine during operations (e.g. 5 + \'5\' = \'55\').',
      code: 'console.log(1 == \'1\'); // true (coercion)\nconsole.log(1 === \'1\'); // false (strict comparison)',
      tags: ['coercion', 'types'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'object-creation-ways',
      x: -1500,
      y: 960,
      width: 340,
      height: 270,
      title: '4. Ways to Create Objects',
      content: 'There are multiple ways to create objects in JS:\n1. Object Literal: {}\n2. Object Constructor: new Object()\n3. Object.create(): Using a prototype\n4. ES6 Classes: class syntax\n5. Constructor functions',
      code: 'const obj = Object.create({ protoVal: 1 });\nconsole.log(obj.protoVal); // 1',
      tags: ['objects', 'syntax'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'engine-parse-compile',
      x: -1050,
      y: 0,
      width: 340,
      height: 270,
      title: '5. How JS Engine Compiles Code',
      content: '1. Parsing: Source code is parsed into tokens and turned into an Abstract Syntax Tree (AST).\n2. Interpretation: An interpreter (Ignition in V8) generates bytecode.\n3. JIT Compilation: A compiler (TurboFan) optimizes hot bytecode into machine code.',
      code: '// JS is compiled right before it is run\nconsole.log(\'JIT Compilation in action!\');',
      tags: ['engine', 'v8', 'compiler'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'execution-context',
      x: -1050,
      y: 320,
      width: 340,
      height: 270,
      title: '6. Execution Context',
      content: 'An Execution Context is the environment in which JS code is evaluated and executed.\n\nPhases:\n1. Memory Creation Phase: Allocates space for variables and functions (hoisting).\n2. Code Execution Phase: Executes code line-by-line.',
      code: '// Context holds variables & this\nconst contextValue = \'Global Context\';',
      tags: ['execution', 'scope'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'callstack',
      x: -1050,
      y: 640,
      width: 340,
      height: 270,
      title: '7. Call Stack',
      content: 'The Call Stack is a LIFO (Last In, First Out) stack that tracks the execution context of functions.\n\nWhen a function is called, its context is pushed to the stack. When it returns, it is popped off.',
      code: 'function first() { second(); }\nfunction second() { console.log(\'stack\'); }\nfirst();',
      tags: ['stack', 'execution'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'strict-mode',
      x: -1050,
      y: 960,
      width: 340,
      height: 270,
      title: '8. Strict Mode',
      content: 'Strict Mode (\'use strict\') opts into a restricted variant of JS.\n\nIt throws silent errors, prevents accidental globals, blocks duplicate parameter names, and disables using keywords as names.',
      code: '\'use strict\';\n// x = 10; // ReferenceError: x is not defined',
      tags: ['standards', 'strict'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'js-single-thread',
      x: -600,
      y: 0,
      width: 340,
      height: 270,
      title: '9. Single-Threaded JS',
      content: 'JS is a single-threaded language, meaning it has only one Call Stack and executes one instruction at a time.\n\nIt handles concurrency using an Event Loop to hand off blocking tasks to Web APIs/libuv.',
      code: '// Sync blocking halts execution\nconsole.log(\'Synchronous thread!\');',
      tags: ['concurrency', 'async'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'var-let-const',
      x: -600,
      y: 320,
      width: 340,
      height: 270,
      title: '10. Var, Let, Const',
      content: '- var: Function scoped, hoisted, can be re-declared and updated.\n- let: Block scoped, hoisted (in TDZ), cannot be re-declared, can be updated.\n- const: Block scoped, hoisted (in TDZ), cannot be updated or re-declared.',
      code: 'var x = 1; let y = 2; const z = 3;\nx = 10; y = 20; // z = 30 throws Error',
      tags: ['basics', 'variables'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'tdz',
      x: -600,
      y: 640,
      width: 340,
      height: 270,
      title: '11. Temporal Dead Zone',
      content: 'The Temporal Dead Zone (TDZ) is the period between block entry and let/const declaration initialization.\n\nAccessing a variable in the TDZ throws a ReferenceError.',
      code: '// console.log(a); // ReferenceError\nlet a = 10;',
      tags: ['variables', 'tdz'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'hoisting',
      x: -600,
      y: 960,
      width: 340,
      height: 270,
      title: '12. Hoisting',
      content: 'Hoisting is the JS engine mechanism where variable and function declarations are moved to the top of their scope during creation.\n\n- var hoisted as undefined.\n- let/const hoisted without initialization.\n- function declarations fully hoisted.',
      code: 'console.log(myVar); // undefined\nvar myVar = 5;\nconsole.log(greet()); // \'Hello\'\nfunction greet() { return \'Hello\'; }',
      tags: ['hoisting', 'execution'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'variable-shadowing',
      x: -600,
      y: 1280,
      width: 340,
      height: 270,
      title: '13. Variable Shadowing',
      content: 'Variable shadowing occurs when a variable declared in an inner scope has the same name as a variable in an outer scope.\n\nThe inner variable masks (shadows) the outer variable within that scope.',
      code: 'let x = 10;\nif (true) {\n  let x = 20; // shadows outer x\n  console.log(x); // 20\n}\nconsole.log(x); // 10',
      tags: ['variables', 'scope'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'scope',
      x: -150,
      y: 0,
      width: 340,
      height: 270,
      title: '14. Scope in JS',
      content: 'Scope determines the visibility and accessibility of variables in your code.\n\nIf a variable is out of scope, it cannot be accessed.',
      code: 'function check() { const scoped = 1; }\n// console.log(scoped); // Error',
      tags: ['scope', 'variables'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'scope-types',
      x: -150,
      y: 320,
      width: 340,
      height: 270,
      title: '15. Types of Scope',
      content: '1. Global Scope: Accessible everywhere.\n2. Function Scope: Accessible inside function.\n3. Block Scope: Accessible inside {} brackets (let/const).\n4. Module Scope: Accessible inside module file.',
      code: '{ let block = \'block\'; } // block scoped',
      tags: ['scope', 'block'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'scope-chaining',
      x: -150,
      y: 640,
      width: 340,
      height: 270,
      title: '16. Scope Chaining',
      content: 'Scope Chaining is the traversal process JS uses to resolve variable values.\n\nIf a variable is not found in local scope, JS checks the outer lexical environment, resolving up to the global scope.',
      code: 'let name = \'Global\';\nfunction outer() {\n  function inner() { console.log(name); } // looks up scope chain\n  inner();\n}\nouter();',
      tags: ['scope', 'resolution'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'closures',
      x: -150,
      y: 960,
      width: 340,
      height: 270,
      title: '17. Closures',
      content: 'A closure is a function that remembers its outer lexical environment variables even after the outer function has completed execution.\n\nCreates a persistent reference to the enclosing variables.',
      code: 'function outer() {\n  let secret = \'secret\';\n  return () => secret;\n}\nconst getSecret = outer();\nconsole.log(getSecret()); // \'secret\'',
      tags: ['closures', 'scope'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'first-class-functions',
      x: 300,
      y: 0,
      width: 340,
      height: 270,
      title: '18. First-Class Functions',
      content: 'Functions are First-Class Citizens in JS. This means they can be:\n1. Assigned to variables.\n2. Passed as arguments to other functions.\n3. Returned from other functions.',
      code: 'const greet = () => \'Hello\';\nconst exec = (fn) => console.log(fn());\nexec(greet); // passed as argument',
      tags: ['functions', 'first-class'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'function-types',
      x: 300,
      y: 320,
      width: 340,
      height: 270,
      title: '19. Types of Functions',
      content: '- Function Statement (Declaration)\n- Function Expression: Assigned to variable\n- Anonymous Function: Function without name\n- Named Function Expression\n- Arrow Function: Compact syntax, lexical this',
      code: 'function decl() {} // declaration\nconst expr = function() {} // expression',
      tags: ['functions', 'syntax'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'iife',
      x: 300,
      y: 640,
      width: 340,
      height: 270,
      title: '20. IIFE',
      content: 'An Immediately Invoked Function Expression (IIFE) is a function that runs as soon as it is defined.\n\nUsed to isolate variables from the global scope.',
      code: '(() => {\n  let privateVar = \'IIFE\';\n  console.log(privateVar);\n})();',
      tags: ['iife', 'execution'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'higher-order-functions',
      x: 300,
      y: 960,
      width: 340,
      height: 270,
      title: '21. Higher-Order Functions',
      content: 'A Higher-Order Function is a function that takes one or more functions as arguments, or returns a function as its result.\n\nE.g. map, filter, reduce.',
      code: 'const numbers = [1, 2];\nconst doubled = numbers.map(x => x * 2);\nconsole.log(doubled); // [2, 4]',
      tags: ['functions', 'higher-order'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'currying',
      x: 300,
      y: 1280,
      width: 340,
      height: 270,
      title: '22. Currying',
      content: 'Currying is a technique of translating a function that takes multiple arguments into a sequence of nested functions, each taking a single argument.',
      code: 'const curryAdd = a => b => a + b;\nconst addFive = curryAdd(5);\nconsole.log(addFive(3)); // 8',
      tags: ['currying', 'fp'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'memoization',
      x: 300,
      y: 1600,
      width: 340,
      height: 270,
      title: '23. Memoization',
      content: 'Memoization is an optimization technique that speeds up programs by caching the results of expensive function calls and returning the cached result when the same inputs occur.',
      code: 'const memoize = (fn) => {\n  const cache = {};\n  return (...args) => {\n    const key = JSON.stringify(args);\n    if (cache[key]) return cache[key];\n    cache[key] = fn(...args);\n    return cache[key];\n  };\n};',
      tags: ['optimization', 'caching'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'prototypes',
      x: 750,
      y: 0,
      width: 340,
      height: 270,
      title: '24. Prototypes',
      content: 'Prototypes are the mechanism by which JavaScript objects inherit features from one another.\n\nEvery object has a prototype template link. Traversed when properties are requested.',
      code: 'const prototypeObj = { role: \'admin\' };\nconst user = Object.create(prototypeObj);\nconsole.log(user.role); // \'admin\'',
      tags: ['prototype', 'oop'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'this-keyword',
      x: 750,
      y: 320,
      width: 340,
      height: 270,
      title: '25. "this" Keyword Context',
      content: 'In JS, "this" refers to the object that is executing the current block of code.\n\nDetermined dynamically by call site execution context (implicit/explicit call/apply/bind).',
      code: 'function show() { console.log(this); }\nconst customObj = { show };\ncustomObj.show(); // customObj',
      tags: ['this', 'context'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'rest-spread',
      x: 750,
      y: 640,
      width: 340,
      height: 270,
      title: '26. Rest & Spread',
      content: '- Spread Operator (...): Expands an iterable into individual elements.\n- Rest Operator (...): Condenses multiple elements into an array.',
      code: 'const arr = [1, 2]; const newArr = [...arr, 3]; // Spread\nconst sum = (...args) => args.reduce((a, b) => a+b); // Rest',
      tags: ['syntax', 'arrays'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'callbacks',
      x: 1200,
      y: 0,
      width: 340,
      height: 270,
      title: '27. Callbacks',
      content: 'A callback function is a function passed into another function as an argument, which is then invoked inside the outer function to complete some routine or action.',
      code: 'function process(callback) { callback(); }\nprocess(() => console.log(\'callback\'));',
      tags: ['async', 'callbacks'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'callback-hell',
      x: 1200,
      y: 320,
      width: 340,
      height: 270,
      title: '28. Callback Hell',
      content: 'Callback Hell is an anti-pattern consisting of multiple nested callback functions, making code hard to read, maintain, and debug. Often called the Pyramid of Doom.',
      code: 'firstCall(() => {\n  secondCall(() => {\n    thirdCall(() => {\n      console.log(\'pyramid\');\n    });\n  });\n});',
      tags: ['async', 'anti-pattern'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'promises',
      x: 1200,
      y: 640,
      width: 340,
      height: 270,
      title: '29. Promises',
      content: 'A Promise is an object representing the eventual completion or failure of an asynchronous operation.\n\nStates: Pending, Fulfilled, Rejected.',
      code: 'const myPromise = new Promise((resolve) => {\n  setTimeout(() => resolve(\'Ready\'), 1000);\n});',
      tags: ['promises', 'async'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'then-catch',
      x: 1200,
      y: 960,
      width: 340,
      height: 270,
      title: '30. Then & Catch',
      content: '- .then(): Attaches handlers for promise resolution (success).\n- .catch(): Attaches handlers for promise rejection (errors).\n- .finally(): Attaches handler running after settling.',
      code: 'myPromise\n  .then(res => console.log(res))\n  .catch(err => console.error(err));',
      tags: ['promises', 'handling'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'async-await',
      x: 1200,
      y: 1280,
      width: 340,
      height: 270,
      title: '31. Async / Await',
      content: 'Async/Await is a syntax that lets you write async promise-based code as if it were synchronous.\n\n- async functions return promises.\n- await pauses function execution for resolving.',
      code: 'async function load() {\n  const res = await myPromise;\n  console.log(res);\n}\nload();',
      tags: ['async', 'await'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'event-loop',
      x: 1650,
      y: 0,
      width: 340,
      height: 270,
      title: '32. Event Loop',
      content: 'The Event Loop is the mechanism that coordinates async tasks execution in JS.\n\nIt monitors the Call Stack. If empty, it pushes callbacks from queues onto the stack.',
      code: '// Event Loop drives JavaScript async runtime',
      tags: ['event-loop', 'execution'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'callback-queue',
      x: 1650,
      y: 320,
      width: 340,
      height: 270,
      title: '33. Callback (Task) Queue',
      content: 'The Callback Queue (or Macrotask Queue) holds callback tasks from Web APIs like setTimeout, setInterval, postMessage.\n\nProcessed after the microtask queue is fully cleared.',
      code: 'setTimeout(() => console.log(\'macro\'), 0);',
      tags: ['queues', 'macrotask'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'microtask-queue',
      x: 1650,
      y: 640,
      width: 340,
      height: 270,
      title: '34. Microtask Queue',
      content: 'The Microtask Queue has higher priority than the Macrotask Queue.\n\nHolds Promise callbacks (.then/.catch), MutationObserver, and queueMicrotask. Cleared completely before yielding to render/macrotasks.',
      code: 'Promise.resolve().then(() => console.log(\'micro\'));',
      tags: ['queues', 'microtask'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'generator-functions',
      x: 1650,
      y: 960,
      width: 340,
      height: 270,
      title: '35. Generators',
      content: 'Generators are functions that can be exited and later re-entered, maintaining context state. Defined with function* and suspends execution using the yield keyword.',
      code: 'function* countGen() {\n  yield 1; yield 2;\n}\nconst c = countGen();\nconsole.log(c.next().value); // 1',
      tags: ['generators', 'syntax'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'event-propagation',
      x: 2100,
      y: 0,
      width: 340,
      height: 270,
      title: '36. Event Propagation',
      content: 'Event propagation describes how events travel through the DOM tree.\n\nPhases:\n1. Capturing Phase: Window to Target.\n2. Target Phase: Triggered on element.\n3. Bubbling Phase: Target to Window.',
      code: '// Event propagation phases',
      tags: ['events', 'dom'],
      color: 'rose',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'event-bubbling',
      x: 2100,
      y: 320,
      width: 340,
      height: 270,
      title: '37. Event Bubbling',
      content: 'Event Bubbling means when an event happens on a DOM element, it first runs handlers on it, then bubbles up through its parents up to window.\n\nCan stop using event.stopPropagation().',
      code: 'element.addEventListener(\'click\', (e) => {\n  e.stopPropagation(); // stops bubbling up\n});',
      tags: ['events', 'bubbling'],
      color: 'slate',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'event-delegation',
      x: 2100,
      y: 640,
      width: 340,
      height: 270,
      title: '38. Event Delegation',
      content: 'Event Delegation is an optimization pattern where a single event listener is attached to a parent element to handle events on nested child items via bubbling.',
      code: 'parent.addEventListener(\'click\', (e) => {\n  if (e.target.matches(\'.child-item\')) {\n    console.log(\'Child clicked!\');\n  }\n});',
      tags: ['events', 'delegation'],
      color: 'indigo',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'debounce',
      x: 2100,
      y: 960,
      width: 340,
      height: 270,
      title: '39. Debouncing',
      content: 'Debouncing is a design pattern that limits the execution of a function until a certain amount of time has elapsed since its last invocation.\n\nCommonly used in search bars.',
      code: 'function debounce(fn, delay) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n}',
      tags: ['optimization', 'events'],
      color: 'cyan',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'throttle',
      x: 2100,
      y: 1280,
      width: 340,
      height: 270,
      title: '40. Throttling',
      content: 'Throttling limits the maximum number of times a function can be called over a given time interval. E.g. runs once every 200ms.\n\nCommonly used in window scroll listeners.',
      code: 'function throttle(fn, limit) {\n  let flag = true;\n  return (...args) => {\n    if (flag) {\n      fn(...args);\n      flag = false;\n      setTimeout(() => flag = true, limit);\n    }\n  };\n}',
      tags: ['optimization', 'events'],
      color: 'amber',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    },
    {
      id: 'garbage-collection',
      x: 2100,
      y: 1600,
      width: 340,
      height: 270,
      title: '41. Garbage Collection',
      content: 'Garbage Collection manages heap allocations automatically using a Mark-and-Sweep algorithm.\n\nIt marks reachable objects starting from roots (active call stack, global context) and deallocates (sweeps) unreachable objects.',
      code: '// Unreachable objects are collected\nlet user = { name: \'Bob\' };\nuser = null; // Bob object is collected',
      tags: ['memory', 'gc'],
      color: 'emerald',
      type: 'note',
      cardMode: 'notes',
      notesFontSize: 'medium',
      notesTextColor: 'default',
      notesFontFamily: 'sans'
    }
  ],
  connections: [
    {
      id: 'conn-1',
      fromCardId: 'types-primitive-non',
      fromSide: 'bottom',
      toCardId: 'types-pass-val-ref',
      toSide: 'top',
      label: 'Defines Pass style'
    },
    {
      id: 'conn-2',
      fromCardId: 'types-pass-val-ref',
      fromSide: 'bottom',
      toCardId: 'types-coercion-conversion',
      toSide: 'top',
      label: 'Resolves values'
    },
    {
      id: 'conn-3',
      fromCardId: 'types-coercion-conversion',
      fromSide: 'bottom',
      toCardId: 'object-creation-ways',
      toSide: 'top',
      label: 'Initializes Objects'
    },
    {
      id: 'conn-4',
      fromCardId: 'types-primitive-non',
      fromSide: 'right',
      toCardId: 'engine-parse-compile',
      toSide: 'left',
      label: 'Allocated by engine'
    },
    {
      id: 'conn-5',
      fromCardId: 'engine-parse-compile',
      fromSide: 'bottom',
      toCardId: 'execution-context',
      toSide: 'top',
      label: 'Runs inside'
    },
    {
      id: 'conn-6',
      fromCardId: 'execution-context',
      fromSide: 'bottom',
      toCardId: 'callstack',
      toSide: 'top',
      label: 'Stacked on'
    },
    {
      id: 'conn-7',
      fromCardId: 'callstack',
      fromSide: 'bottom',
      toCardId: 'strict-mode',
      toSide: 'top',
      label: 'Governs syntax rules'
    },
    {
      id: 'conn-8',
      fromCardId: 'engine-parse-compile',
      fromSide: 'right',
      toCardId: 'js-single-thread',
      toSide: 'left',
      label: 'Compiles single thread'
    },
    {
      id: 'conn-9',
      fromCardId: 'js-single-thread',
      fromSide: 'bottom',
      toCardId: 'var-let-const',
      toSide: 'top',
      label: 'Allocates variables'
    },
    {
      id: 'conn-10',
      fromCardId: 'var-let-const',
      fromSide: 'bottom',
      toCardId: 'tdz',
      toSide: 'top',
      label: 'Enforces'
    },
    {
      id: 'conn-11',
      fromCardId: 'tdz',
      fromSide: 'bottom',
      toCardId: 'hoisting',
      toSide: 'top',
      label: 'Limits'
    },
    {
      id: 'conn-12',
      fromCardId: 'hoisting',
      fromSide: 'bottom',
      toCardId: 'variable-shadowing',
      toSide: 'top',
      label: 'Can cause'
    },
    {
      id: 'conn-13',
      fromCardId: 'var-let-const',
      fromSide: 'right',
      toCardId: 'scope',
      toSide: 'left',
      label: 'Binds to scope'
    },
    {
      id: 'conn-14',
      fromCardId: 'scope',
      fromSide: 'bottom',
      toCardId: 'scope-types',
      toSide: 'top',
      label: 'Resolves within'
    },
    {
      id: 'conn-15',
      fromCardId: 'scope-types',
      fromSide: 'bottom',
      toCardId: 'scope-chaining',
      toSide: 'top',
      label: 'Traverses'
    },
    {
      id: 'conn-16',
      fromCardId: 'scope-chaining',
      fromSide: 'bottom',
      toCardId: 'closures',
      toSide: 'top',
      label: 'Forms closure'
    },
    {
      id: 'conn-17',
      fromCardId: 'scope',
      fromSide: 'right',
      toCardId: 'first-class-functions',
      toSide: 'left',
      label: 'Scuffs'
    },
    {
      id: 'conn-18',
      fromCardId: 'first-class-functions',
      fromSide: 'bottom',
      toCardId: 'function-types',
      toSide: 'top',
      label: 'Implements'
    },
    {
      id: 'conn-19',
      fromCardId: 'function-types',
      fromSide: 'bottom',
      toCardId: 'iife',
      toSide: 'top',
      label: 'Self executes'
    },
    {
      id: 'conn-20',
      fromCardId: 'iife',
      fromSide: 'bottom',
      toCardId: 'higher-order-functions',
      toSide: 'top',
      label: 'Delegates'
    },
    {
      id: 'conn-21',
      fromCardId: 'higher-order-functions',
      fromSide: 'bottom',
      toCardId: 'currying',
      toSide: 'top',
      label: 'Facilitates'
    },
    {
      id: 'conn-22',
      fromCardId: 'currying',
      fromSide: 'bottom',
      toCardId: 'memoization',
      toSide: 'top',
      label: 'Caches curried output'
    },
    {
      id: 'conn-23',
      fromCardId: 'function-types',
      fromSide: 'right',
      toCardId: 'prototypes',
      toSide: 'left',
      label: 'Binds prototype'
    },
    {
      id: 'conn-24',
      fromCardId: 'prototypes',
      fromSide: 'bottom',
      toCardId: 'this-keyword',
      toSide: 'top',
      label: 'Evaluates context'
    },
    {
      id: 'conn-25',
      fromCardId: 'this-keyword',
      fromSide: 'bottom',
      toCardId: 'rest-spread',
      toSide: 'top',
      label: 'Spreads params'
    },
    {
      id: 'conn-26',
      fromCardId: 'first-class-functions',
      fromSide: 'right',
      toCardId: 'callbacks',
      toSide: 'left',
      label: 'Passed as callback'
    },
    {
      id: 'conn-27',
      fromCardId: 'callbacks',
      fromSide: 'bottom',
      toCardId: 'callback-hell',
      toSide: 'top',
      label: 'Results in'
    },
    {
      id: 'conn-28',
      fromCardId: 'callback-hell',
      fromSide: 'bottom',
      toCardId: 'promises',
      toSide: 'top',
      label: 'Cleaned up by'
    },
    {
      id: 'conn-29',
      fromCardId: 'promises',
      fromSide: 'bottom',
      toCardId: 'then-catch',
      toSide: 'top',
      label: 'Chained with'
    },
    {
      id: 'conn-30',
      fromCardId: 'then-catch',
      fromSide: 'bottom',
      toCardId: 'async-await',
      toSide: 'top',
      label: 'Sugar coated'
    },
    {
      id: 'conn-31',
      fromCardId: 'callbacks',
      fromSide: 'right',
      toCardId: 'event-loop',
      toSide: 'left',
      label: 'Handles lifecycle'
    },
    {
      id: 'conn-32',
      fromCardId: 'event-loop',
      fromSide: 'bottom',
      toCardId: 'callback-queue',
      toSide: 'top',
      label: 'Pushes macrotasks'
    },
    {
      id: 'conn-33',
      fromCardId: 'callback-queue',
      fromSide: 'bottom',
      toCardId: 'microtask-queue',
      toSide: 'top',
      label: 'Prioritized by'
    },
    {
      id: 'conn-34',
      fromCardId: 'microtask-queue',
      fromSide: 'bottom',
      toCardId: 'generator-functions',
      toSide: 'top',
      label: 'Suspends execution'
    },
    {
      id: 'conn-35',
      fromCardId: 'callbacks',
      fromSide: 'right',
      toCardId: 'event-propagation',
      toSide: 'left',
      label: 'Fires DOM events'
    },
    {
      id: 'conn-36',
      fromCardId: 'event-propagation',
      fromSide: 'bottom',
      toCardId: 'event-bubbling',
      toSide: 'top',
      label: 'Triggers bubbling'
    },
    {
      id: 'conn-37',
      fromCardId: 'event-bubbling',
      fromSide: 'bottom',
      toCardId: 'event-delegation',
      toSide: 'top',
      label: 'Delegated at parents'
    },
    {
      id: 'conn-38',
      fromCardId: 'event-delegation',
      fromSide: 'bottom',
      toCardId: 'debounce',
      toSide: 'top',
      label: 'Optimized via'
    },
    {
      id: 'conn-39',
      fromCardId: 'debounce',
      fromSide: 'bottom',
      toCardId: 'throttle',
      toSide: 'top',
      label: 'Throttles triggers'
    },
    {
      id: 'conn-40',
      fromCardId: 'throttle',
      fromSide: 'bottom',
      toCardId: 'garbage-collection',
      toSide: 'top',
      label: 'GC sweeps memory leaks'
    }
  ]
};

const runSeeder = async () => {
  console.log('Connecting to database...');
  await connectDB(MONGO_URI);

  try {
    console.log('Creating seeded Javascript board...');
    const board = await createBoard(seedData.name, 'way2hell', 'partial');
    
    console.log('Populating JS board nodes & connections...');
    await updateBoard(board._id, seedData);

    console.log('Successfully seeded "JavaScript" whiteboard!');
  } catch (err) {
    console.error('Failed to seed database:', err);
  } finally {
    // Terminate DB connections
    await mongoose.disconnect();
    console.log('Database connection closed.');
    process.exit(0);
  }
};

runSeeder();
